# load("@build_bazel_rules_typescript//:defs.bzl", "ts_library", "ts_devserver")

# ts_devserver(
#     name = "devserver",
#     bootstrap = ["@build_bazel_rules_typescript//:protobufjs_bootstrap_scripts"],
#     entry_module = "bootcamp/typescript/app",
#     port = 8080,
#     deps = [":app"],
# )

exports_files(["tsconfig.json"])
