# load("@npm_bazel_typescript//:index.bzl", "ts_library", "ts_devserver")

# ts_devserver(
#     name = "devserver",
#     bootstrap = ["@npm_bazel_typescript//:protobufjs_bootstrap_scripts"],
#     entry_module = "bootcamp/typescript/app",
#     port = 8080,
#     deps = [":app"],
# )

# exports_files(["tsconfig.json"])