package(default_visibility = ["//visibility:public"])

# load("@io_grpc_grpc_java//:java_grpc_library.bzl", "java_grpc_library")
# load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
# load("@npm_bazel_typescript//:index.bzl", "ts_proto_library")
