// @generated by protoc-gen-es v1.10.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/logger/logger.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message LogMessage
 */
export declare class LogMessage extends Message<LogMessage> {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: int64 time = 2;
   */
  time: bigint;

  constructor(data?: PartialMessage<LogMessage>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "LogMessage";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogMessage;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogMessage;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogMessage;

  static equals(a: LogMessage | PlainMessage<LogMessage> | undefined, b: LogMessage | PlainMessage<LogMessage> | undefined): boolean;
}

/**
 * @generated from message Empty
 */
export declare class Empty extends Message<Empty> {
  constructor(data?: PartialMessage<Empty>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Empty";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Empty;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Empty;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Empty;

  static equals(a: Empty | PlainMessage<Empty> | undefined, b: Empty | PlainMessage<Empty> | undefined): boolean;
}

