# load("@rules_java//java:defs.bzl", "java_binary", "java_library", "java_test")

# deps you may need for various targets
#    "@io_grpc_grpc_java//core",
#    "@io_grpc_grpc_java//netty",
#    "@junit_junit//jar" - optional
