name: bazel-build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-bazel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - run: bin/lab install_all
      - run: nix-shell --pure --run "bazel test //tests:integration_test"
